### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by SitiSchu** [adrianpueyo/Stamps#1]
Hi,

checking the LICENSE file it specifies that the code is GPL-3.0 but the license in the pdf seems to be the 2-Clause BSD License. 

Which license is the code under ?

**Comment by adrianpueyo** [comment]
Hi Simon,

Thanks for your question. My mistake! The one on the pdf is correct.

Thanks,

Adrian

**Comment by SitiSchu** [comment]
Good to hear, would you mind updating the LICENSE file in the repo or should I quickly make a Pull Request ?

**Comment by adrianpueyo** [comment]
Sure! Happy if you’d like to do a pull request :)

Thanks Simon.
