### ISSUE TITLE
Nuke 13.0v2 Python 3 error during load

### ISSUE THREAD

**Issue by backhausmartin** [adrianpueyo/Stamps#4]
Hi, I am getting an error using Nuke 13.0v2 (which should be Python 3 now) during the startup (on Windows 10):

```
Traceback (most recent call last):
  File "C:/Users/martin/.nuke/menu.py", line 34, in <module>
    import stamps
  File "C:/Users/martin/.nuke\stamps.py", line 35, in <module>
    if not globals().has_key('Stamps_LastCreated'):
AttributeError: 'dict' object has no attribute 'has_key'
```

Nuke 13 does not start at all, when I try to load stamps in menu.py

**Comment by adrianpueyo** [comment]
Could you try the develop branch? Should have that fixed - still pending tests.

Thanks!

**Comment by backhausmartin** [comment]
Yes, it loads with the develop branch.
I also loaded one older script with stamps present and everything seems to be fine.
Thank you! 👍

**Comment by melMass** [comment]
This can be closed @backhausmartin

**Comment by adrianpueyo** [comment]
Thanks!
